name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/cache@v4
        with:
          # build should be beside of git repo because it's submodule must be a empty dir when init.
          path: out/windows/x64/obj
          key: ${{ runner.os }}-skia-build-cache
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: Clone source
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          mkdir -p skiasharp && cd skiasharp
          git init && git remote add origin https://github.com/mono/SkiaSharp.git
          git fetch --depth 1 origin release/3.0.0-preview.4
          git checkout --recurse-submodules -q FETCH_HEAD
          git submodule update --init --depth 1

      - name: Prepare build skia
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
          New-Item out\windows\x64\ -ItemType Directory -ea 0
          cp args.gn out\windows\x64\
          cd skiasharp\externals\skia
          python tools\git-sync-deps
          python ..\depot_tools\gn.py gen "${{github.workspace}}/out/windows/x64" --args="target_os=\"win\" target_cpu=\"x64\" is_static_skiasharp=true skia_enable_fontmgr_win_gdi=false skia_use_dng_sdk=true skia_use_icu=false skia_use_piex=true skia_use_sfntly=false skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_vulkan=true skia_use_angle=true skia_enable_skottie=true skia_enable_gpu=true clang_win=\"C:/Program Files/LLVM/\" extra_cflags=[ \"-DSKIA_C_DLL\", \"/MT\", \"/EHsc\", \"/Z7\", \"-D_HAS_AUTO_PTR_ETC=1\" ]"

      - name: Build skia
        working-directory: ${{github.workspace}}
        run: |
          cd skiasharp\externals\skia
          ..\depot_tools\ninja -C ${{github.workspace}}\out\windows\x64\ SkiaSharp
          cd ${{github.workspace}}\out\windows\x64\
          lib.exe /OUT:libSkiaSharp.lib *.lib

      - name: Build libHarfBuzzSharp
        working-directory: ${{github.workspace}}
        shell: cmd
        run: |
          cd skiasharp\native\windows\libHarfBuzzSharp
          msbuild -m -t:rebuild -p:Configuration=Release;Platform=x64;ConfigurationType=StaticLibrary;WindowsTargetPlatformVersion=10.0.19041.0;PlatformToolset=v143

      - name: Package libSkiaSharp
        working-directory: ${{github.workspace}}
        run: |
          cd ${{github.workspace}}\out\windows\x64\
          7z a -y -mx9 libSkiaSharp.7z ./libSkiaSharp.lib

      - name: Package libHarfBuzzSharp
        working-directory: ${{github.workspace}}
        run: |
          cd skiasharp\native\windows\libHarfBuzzSharp\bin\x64\Release
          7z a -y -mx9 libHarfBuzzSharp.7z ./libHarfBuzzSharp.lib

      - uses: actions/upload-artifact@v4
        with:
          name: libSkiaSharp
          path: out/windows/x64/libSkiaSharp.7z

      - uses: actions/upload-artifact@v4
        with:
          name: libHarfBuzzSharp
          path: skiasharp/native/windows/libHarfBuzzSharp/bin/x64/Release/libHarfBuzzSharp.7z

